-- Review before applying. No existing user data is imported by this migration.
create table public.memos (
  id uuid primary key,
  author text not null check (author in ('kongdol', 'kongsun')),
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);
create index memos_created_at_idx on public.memos (created_at desc);
create table public.weight_records (
  record_date date primary key,
  kg numeric not null check (kg > 0 and kg < 1000),
  updated_at timestamptz not null default now()
);
alter table public.memos enable row level security;
alter table public.weight_records enable row level security;
revoke all on public.memos, public.weight_records from anon, authenticated;
grant select on public.memos, public.weight_records to anon, authenticated;
grant all on public.memos, public.weight_records to service_role;
create policy public_read_memos on public.memos for select to anon, authenticated using (true);
create policy public_read_weights on public.weight_records for select to anon, authenticated using (true);

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create table private.write_limits (
  bucket text primary key,
  window_started timestamptz not null,
  attempts integer not null
);
alter table private.write_limits enable row level security;
revoke all on private.write_limits from public, anon, authenticated;
-- A durable global bucket protects against distributed guessing and forged IPs.
-- All requests count, including valid writes. Atomic row locks survive cold starts.
create function public.consume_write_budget(ip_digest text) returns boolean
language plpgsql security invoker set search_path = '' as $$
declare
  v_now timestamptz := clock_timestamp();
  v_global private.write_limits%rowtype;
  v_ip private.write_limits%rowtype;
begin
  if ip_digest !~ '^[0-9a-f]{64}$' then return false; end if;
  insert into private.write_limits values ('global', v_now, 0) on conflict do nothing;
  select * into v_global from private.write_limits where bucket = 'global' for update;
  if v_global.window_started <= v_now - interval '1 hour' then
    update private.write_limits set window_started = v_now, attempts = 0 where bucket = 'global';
    v_global.attempts := 0;
  end if;
  if v_global.attempts >= 30 then return false; end if;
  update private.write_limits set attempts = attempts + 1 where bucket = 'global';
  delete from private.write_limits where bucket <> 'global' and window_started < v_now - interval '2 days';
  insert into private.write_limits values ('ip:' || ip_digest, v_now, 0) on conflict do nothing;
  select * into v_ip from private.write_limits where bucket = 'ip:' || ip_digest for update;
  if v_ip.window_started <= v_now - interval '15 minutes' then
    update private.write_limits set window_started = v_now, attempts = 0 where bucket = 'ip:' || ip_digest;
    v_ip.attempts := 0;
  end if;
  if v_ip.attempts >= 5 then return false; end if;
  update private.write_limits set attempts = attempts + 1 where bucket = 'ip:' || ip_digest;
  return true;
end;
$$;
revoke all on function public.consume_write_budget(text) from public, anon, authenticated;
grant execute on function public.consume_write_budget(text) to service_role;

-- Date is generated by the database, never accepted from a browser.
create function public.save_today_weight(weight_kg numeric) returns public.weight_records
language plpgsql security invoker set search_path = '' as $$
declare v_row public.weight_records;
begin
  insert into public.weight_records (record_date, kg)
  values ((clock_timestamp() at time zone 'Asia/Seoul')::date, weight_kg)
  on conflict (record_date) do update set kg = excluded.kg, updated_at = clock_timestamp()
  returning * into v_row;
  return v_row;
end;
$$;
revoke all on function public.save_today_weight(numeric) from public, anon, authenticated;
grant execute on function public.save_today_weight(numeric) to service_role;


-- Private author management. Only bcrypt hashes are stored, never raw codes.
create table private.author_codes (
  author text primary key check (author in ('kongdol', 'kongsun')),
  code_hash text not null check (code_hash ~ '^\$2[aby]\$')
);
alter table private.author_codes enable row level security;
revoke all on private.author_codes from public, anon, authenticated;
create function public.verify_author_code(submitted_code text) returns text
language plpgsql security invoker set search_path = '' as $$
declare v_count integer; v_author text;
begin
  if submitted_code !~ '^[0-9]{4}$' then return null; end if;
  select count(*), min(author) into v_count, v_author
  from private.author_codes
  where extensions.crypt(submitted_code, code_hash) = code_hash;
  -- Duplicate codes fail closed even though salted hashes are different.
  if v_count = 1 then return v_author; end if;
  return null;
end;
$$;
revoke all on function public.verify_author_code(text) from public, anon, authenticated;
grant execute on function public.verify_author_code(text) to service_role;

grant usage on schema private to service_role;
grant select, insert, update, delete on private.write_limits to service_role;
grant select on private.author_codes to service_role;
revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
